### PR TITLE
Add github action for releasing

### PR DESCRIPTION
**Pull request by f-moya**
Thought to be used along with:
- https://github.com/codeclimate/codeclimate/pull/1013/commits/ab50189b00506b29da065706ff665293d02be236
- https://github.com/codeclimate/codeclimate/pull/1013/commits/d490c3deffa25013eadfae97cc9cd86848ecd67b

### CODE REVIEW

**Review by filipesperandio — APPROVED** [review]

**Comment by f-moya** [comment]
@filipesperandio could you please merge this one ? I guess the repo is outside of github's Quality team.

**Comment by f-moya** [comment]
@fede-moya sorry to bother again

**Comment by f-moya** [comment]
@filipesperandio 🙌🏼

**Comment by f-moya** [comment]
@filipesperandio
please

**Comment by filipesperandio** [comment]
@fede-moya oh, missed a few notifications here... added the codeclimate/quality team to the repo, can you try merging now?

**Comment by f-moya** [comment]
@filipesperandio merged, thank you !!

**Pull request merged**
